Changes exported constants naming convention.
SkynetLabs/skynet-js pull request #236
Opened 2021-08-06 03:48 UTC by amberm31

2021-08-06 03:57 UTC, m-cat commented
The failing checks are not due to this Pull Request and will be fixed by https://github.com/SkynetLabs/skynet-js/pull/235.

2021-08-06 04:00 UTC, m-cat commented on src/registry.ts
> +export const REGEX_REVISION_WITH_QUOTES = /"revision":\s*"([0-9]+)"/;
This shouldn't be exported if the original const was not exported. Same with `regexRevisionWithQuotes` below.

```suggestion
const REGEX_REVISION_WITH_QUOTES = /"revision":\s*"([0-9]+)"/;
```

2021-08-06 04:00 UTC, m-cat commented on src/registry.ts
> +export const regexRevisionWithQuotes = REGEX_REVISION_WITH_QUOTES;
```suggestion
const regexRevisionWithQuotes = REGEX_REVISION_WITH_QUOTES;
```

2021-08-06 04:05 UTC, m-cat requested changes
Looks fantastic! Just a couple minor changes needed. Thank you for your contribution, and welcome to GitHub!

2021-08-06 18:49 UTC, m-cat approved these changes
Great job!

2021-08-09 09:39 UTC, kwypchlo approved these changes

2021-08-09 10:23 UTC, peterjan approved these changes

2021-08-09 10:26 UTC, peterjan commented
I like that we're introducing this naming convention! 

Something that might be useful to introduce in the future is a `consts.deprecated.ts` file where we gather all deprecated constants. The obvious benefit is that we don't have all these old constants in our "live" codebase, and we get rid of those nasty deprecation warnings.

2021-08-09 17:03 UTC, merged