Separated Integration Test Files
SkynetLabs/skynet-js pull request #296
Opened 2021-09-21 21:44 UTC by AmberMichaelis

# PULL REQUEST

## Overview

## Issues Closed

Closes #203

2021-09-22 00:39 UTC, m-cat approved these changes
Fantastic work!

2021-09-22 00:49 UTC, m-cat approved these changes
Fabulous work!

2021-09-22 20:41 UTC, kwypchlo requested changes
I started doing a code review from the bottom for some reason and started to point out all `{ [key: string]: string | undefined }` types - we should not enforce the value to be a string, we should keep accepting number and boolean, otherwise it's a breaking change, unnecessary too

2021-09-22 20:41 UTC, kwypchlo commented on src/utils/url.test.ts
> +  const parts: Array<[string, { [key: string]: string | undefined }, string]> = [
```suggestion
  const parts: Array<[string, { [key: string]: string | number | boolean }, string]> = [
```

we should keep supporting all basic types - namely numbers and booleans

2021-09-22 20:41 UTC, kwypchlo commented on src/utils/url.ts
> +export function addUrlQuery(url: string, query: { [key: string]: string | undefined }): string {
```suggestion
export function addUrlQuery(url: string, query: { [key: string]: string | number | boolean }): string {
```

is undefined possible here? in any case we should keep supporting all basic types - namely numbers and booleans included

2021-09-22 20:41 UTC, kwypchlo commented on src/upload.ts
> +  const query: { [key: string]: string | undefined } = { filename };
```suggestion
  const query: { [key: string]: string | number | boolean } = { filename };
```

2021-09-22 20:41 UTC, kwypchlo commented on src/registry.ts
> +    timeout: DEFAULT_GET_ENTRY_TIMEOUT.toString(),
```suggestion
    timeout: DEFAULT_GET_ENTRY_TIMEOUT,
```

`makeUrl` should be happy to accept numbers

2021-09-22 20:41 UTC, kwypchlo commented on src/download.ts
> +  const query: { [key: string]: string | undefined } = {};
```suggestion
  const query: { [key: string]: string | number | boolean } = {};
```

2021-09-22 20:41 UTC, kwypchlo commented on src/download.ts
> +    query.attachment = "true";
```suggestion
    query.attachment = true;
```

`addUrlQuery` should be happy to accept numbers and booleans

2021-09-22 20:42 UTC, kwypchlo requested changes

2021-09-22 20:42 UTC, kwypchlo commented on src/download.ts
> +    query.attachment = "true";
```suggestion
    query.attachment = true;
```

2021-09-22 20:42 UTC, kwypchlo commented on src/download.ts
> +  const query: { [key: string]: string | undefined } = {};
```suggestion
  const query: { [key: string]: string | number | boolean } = {};
```

2021-09-22 20:42 UTC, kwypchlo commented on src/client.ts
> +  query?: { [key: string]: string | undefined }
```suggestion
  query?: { [key: string]: string | number | boolean }
```

2021-09-22 20:42 UTC, kwypchlo commented on src/client.ts
> +  query?: { [key: string]: string | undefined };
```suggestion
  query?: { [key: string]: string | number | boolean };
```

2021-09-22 21:28 UTC, m-cat commented
For reference:

I made this change for them because one of the dependencies (`url-parse` I think) got updated (or the types got updated) and they were getting a lint error. I figure that fixing all the internal types would be fine because it's only internal. Otherwise I would have had to do a `// @ts-ignore` and I'm trying to minimize those, as much as possible.

2021-09-29 11:05 UTC, kwypchlo submitted a review, later dismissed
ok I think overall it's fine, I had to read the source code thoroughly but it seems like in fact those methods that accept string values are not exposed anywhere, still feels weird and unnatural but works

2021-10-11 21:24 UTC, merged