Allow custom cookie in integration tests
SkynetLabs/skynet-js pull request #384
Opened 2022-02-02 21:03 UTC by m-cat

# PULL REQUEST

## Overview

Add possibility to authenticate in skynet-js integration tests.

2022-02-03 11:03 UTC, kwypchlo requested changes

2022-02-03 11:03 UTC, kwypchlo commented on integration/index.ts
> +export const customCookie = process.env.SKYNET_JS_INTEGRATION_TEST_CUSTOM_COOKIE || undefined;
```suggestion
export const customCookie = process.env.SKYNET_JS_INTEGRATION_TEST_CUSTOM_COOKIE;
```

undefined is already the default

2022-02-04 15:08 UTC, kwypchlo approved these changes

2022-02-07 11:10 UTC, ro-tex approved these changes

2022-02-07 11:10 UTC, merged